dashboard/urls.py
from django.urls import path, re_path

from .views import Admin, Common, Customers

urlpatterns = [

    path('api-notification/', Common.notif_api, name="notif_api"),
    re_path(r'^api-complaint/(?P<slug>[\w-]+)/$', Common.complaint_api),

    path('dashboard/', Customers.dashboard, name='customer_dashboard'),
    path('track-complaint/', Customers.track_complaint,
         name='customer_track_complaint'),
    path('edit-profile/', Customers.edit_profile, name='customer_edit_profile'),
    path('submit-feedback/', Customers.submit_feedback, name="submit_feedback"),

    path('admin/dashboard', Admin.dashboard, name='admin_dashboard'),
    re_path(r'^admin/complaints/$', Admin.complaints, name='admin_complaints'),
    path('admin/reminders/', Admin.reminders, name='admin_reminders'),
    path('admin/fms-users/', Admin.fms_users, name='admin_fms_users'),
    path('admin/charts/', Admin.charts, name='admin_charts'),
    path('admin/notifications/', Admin.notifications, name='admin_notifications'),
    path('admin/complaint-reminder/', Admin.set_complaint_reminder,
         name='set_complaint_reminder'),
    path('admin/settings/', Admin.settings, name='admin_settings'),
    path('admin/edit-profile/', Admin.edit_profile, name='admin_edit_profile'),
    path('complaint-action/', Admin.complaint_action, name='complaint_action'),
    path('notification-action/', Admin.notification_action,
         name='notification_action'),
    path('complaint-category-action/', Admin.complaint_category_action,
         name='complaint_category_action'),
    path('location-choice-action/', Admin.location_choice_action,
         name='location_choice_action'),
    path('fms-user-action/', Admin.fms_user_action,
         name='fms_user_action'),
    re_path(r'^last-complaint/(?P<slug>[\w-]+)/$', Admin.last_complaint),

]

fms/urls.py
from authentication.views import CustomerSignUpView
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.urls import urlpatterns
from django.shortcuts import redirect
from django.urls import include, path

from .views import (HomeView, LoginRedirectView, LogoutView, MainOSAAPP,
                    PasswordResetView, SignUpView)

urlpatterns = [
    #     path('admin/', admin.site.urls),
    path('', HomeView, name='index'),
    path('login_redirects/', LoginRedirectView, name='login-redirects'),
    path('', include('dashboard.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    #     path('accounts/signup/customer/',
    #          CustomerSignUpView, name='customer_signup'),
    #     path('password_reset/',
    #          auth_views.PasswordResetView.as_view(
    #              template_name='registration/password_reset_form.html',
    #              html_email_template_name="registration/html_password_reset_email.html",
    #              subject_template_name="registration/password_reset_subject.txt",
    #          ), name="password_reset"),
    path('accounts/signup/customer/',
         SignUpView, name='customer_signup'),
    path('password_reset/',
         PasswordResetView, name="password_reset"),
    path('main_osa_app/',
         MainOSAAPP, name="main_osa_app"),
    path('accounts/logout',
         LogoutView, name='logout')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

authentication/models.py
import json

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class User(AbstractUser):

    username_osa = models.CharField(max_length=150, unique=True)
    is_customer = models.BooleanField(default=False)
    is_fms = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'


class Customer(models.Model):

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)
    contact = models.IntegerField(null=True)

    class Meta:
        verbose_name = 'Customer'
        verbose_name_plural = 'Customers'

    def __str__(self):
        return str(self.user.username)


class FMS(models.Model):

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)

    class Meta:
        verbose_name = 'FMS'
        verbose_name_plural = 'FMS'

    def __str__(self):
        return str(self.user.username)

dashboard/views/Admin.py
import csv
from datetime import datetime

from authentication.decorators import fms_required
from authentication.forms import FMSUserForm
from authentication.models import FMS
from dashboard.forms import (ComplaintCategoriesForm, LocationChoicesForm,
                             NotificationForm)
from dashboard.models import (ComplaintCategories,
                              ComplaintCategories_ActiveList, LocationChoices,
                              LocationChoices_ActiveList)
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count, Q
from django.forms.widgets import TextInput
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django_filters import (CharFilter, ChoiceFilter, DateTimeFilter,
                            FilterSet, OrderingFilter)
from django_filters.filters import NumberFilter

from ..models import Complaint, Notification


class ComplaintFilter(FilterSet):

    search = CharFilter(method='custom_search_filter', label='Search', widget=TextInput(
        attrs={'placeholder': 'Search by Complaint ID, Username, Email, Contact'}))
    category = ChoiceFilter(
        field_name='category', empty_label='All', choices=ComplaintCategories_ActiveList(), label='Complaint Category')

    location = ChoiceFilter(field_name='location',
                            empty_label='All', choices=LocationChoices_ActiveList(), label='Complaint Location')

    rating = ChoiceFilter(field_name='rating',
                          empty_label='Any', choices=((1, 1), (2, 2), (3, 3), (4, 4), (5, 5), ), label='Rating')

    created_at = DateTimeFilter(
        field_name='created_at',
        label='Created On/After',
        lookup_expr='gte',
        widget=TextInput(attrs={
                         'type': 'date', 'placeholder': 'DD-MM-YYYY', 'max': datetime.now().date()})
    )

    active = ChoiceFilter(field_name='active', label='Status',
                          empty_label='All', choices=((True, 'Active'), (False, 'Closed')))

    createdSort = OrderingFilter(
        choices=(
            ('created_at', 'Old to New'),
        ), label='Sort By Created', empty_label='New to Old'
    )

    def custom_search_filter(self, queryset, name, value):
        return queryset.filter(
            Q(customer__user__username__contains=value) | Q(
                customer__contact__contains=value) | Q(complaint_id__contains=value) | Q(customer__user__first_name__contains=value) | Q(customer__user__last_name__contains=value)
        )


class ChartFilter(FilterSet):

    category = ChoiceFilter(
        field_name='category', empty_label='All', choices=ComplaintCategories_ActiveList(), label='Complaint Category')

    location = ChoiceFilter(field_name='location',
                            empty_label='All', choices=LocationChoices_ActiveList(), label='Complaint Location')

    rating = ChoiceFilter(field_name='rating',
                          empty_label='Any', choices=((1, 1), (2, 2), (3, 3), (4, 4), (5, 5), ), label='Rating')

    created_at = DateTimeFilter(
        field_name='created_at',
        label='Created On/After',
        lookup_expr='gte',
        widget=TextInput(attrs={
                         'type': 'date', 'placeholder': 'DD-MM-YYYY', 'max': datetime.now().date()})
    )

    year = NumberFilter(field_name='created_at',
                        lookup_expr='year', label="Year", widget=TextInput(attrs={
                            'placeholder': 'Year', 'type': 'number', 'max': datetime.now().date().year}))

    active = ChoiceFilter(field_name='active', label='Status',
                          empty_label='All', choices=((True, 'Active'), (False, 'Closed')))

    def custom_search_filter(self, queryset, name, value):
        return queryset.filter(
            Q(customer__user__username__contains=value) | Q(
                customer__contact__contains=value) | Q(complaint_id__contains=value) | Q(customer__user__first_name__contains=value) | Q(customer__user__last_name__contains=value)
        )


class RemindersFilter(FilterSet):

    search = CharFilter(method='custom_search_filter', label='Search', widget=TextInput(
        attrs={'placeholder': 'Search by Complaint ID, Username, Email, Contact'}))

    category = ChoiceFilter(
        field_name='category', empty_label='All', choices=ComplaintCategories_ActiveList(), label='Complaint Category')

    location = ChoiceFilter(field_name='location',
                            empty_label='All', choices=LocationChoices_ActiveList(), label='Complaint Location')

    rating = ChoiceFilter(field_name='rating',
                          empty_label='Any', choices=((1, 1), (2, 2), (3, 3), (4, 4), (5, 5), ), label='Rating')

    active = ChoiceFilter(field_name='active', label='Status',
                          empty_label='All', choices=((True, 'Active'), (False, 'Closed')))

    createdSort = OrderingFilter(
        choices=(
            ('created_at', 'Old to New'),
        ), label='Sort By Created', empty_label='New to Old'
    )

    def custom_search_filter(self, queryset, name, value):
        return queryset.filter(
            Q(customer__user__username__contains=value) | Q(
                customer__contact__contains=value) | Q(complaint_id__contains=value) | Q(customer__user__first_name__contains=value) | Q(customer__user__last_name__contains=value)
        )


@fms_required
def dashboard(request):

    countActive = Complaint.objects.filter(
        active=True).count()
    countTotal = Complaint.objects.count()

    if countTotal <= 0:
        countTotal = 1

    activePercent = ((countTotal - countActive) * 100) // countTotal

    topComplaints = Complaint.objects.all().order_by('-created_at')[:3]

    yearCount = Complaint.objects.filter(
        created_at__year=datetime.now().year).values_list('created_at__month').annotate(total=Count('pk'))

    yearCounts = [0] * 12
    for (month, count) in yearCount:
        yearCounts[month - 1] = count

    try:
        lastComplaint = Complaint.objects.latest('created_at').complaint_id
    except Complaint.DoesNotExist:
        lastComplaint = 0

    context = {
        "dashboard_link": "active",
        "last_complaint": lastComplaint,
        "activePercent": activePercent,
        "countActive": countTotal - countActive,
        "countTotal": countTotal,
        'complaints': topComplaints,
        'yearCounts': list(yearCounts)
    }

    return render(request, 'admin/dashboard.html', context)


@ fms_required
def complaints(request):

    filtered_complaints = ComplaintFilter(
        request.GET, queryset=Complaint.objects.all().order_by('-created_at')
    )

    paginator = Paginator(filtered_complaints.qs, 18)
    page = request.GET.get('page', 1)

    try:
        res = paginator.page(page)
    except PageNotAnInteger:
        res = paginator.page(1)
    except EmptyPage:
        res = paginator.page(paginator.num_pages)

    context = {
        "complaints_link": "active",
        'filter': filtered_complaints,
        'complaints': res
    }

    return render(request, 'admin/complaints.html', context)


@ fms_required
def charts(request):

    filtered_complaints = ChartFilter(
        request.GET, queryset=Complaint.objects.all()
    )

    yearCount = filtered_complaints.qs.values_list(
        'created_at__month').annotate(total=Count('pk'))

    yearCounts = [0] * 12
    for (month, count) in yearCount:
        yearCounts[month - 1] = count

    context = {
        "charts_link": "active",
        'filter': filtered_complaints,
        'yearCounts': yearCounts
    }

    if request.POST:
        complaints = filtered_complaints.qs
        if len(complaints) > 0:
            keys = complaints[0].csv().keys()
            response = HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="fms-complaints-' + \
                datetime.now().strftime("%Y-%m-%d-%H:%M")+'.csv"'
            writer = csv.writer(response)
            writer.writerow(keys)
            for complaint in filtered_complaints.qs:
                writer.writerow(complaint.csv().values())
            return response
    return render(request, 'admin/charts.html', context)


@ fms_required
def reminders(request):

    filtered_complaints = RemindersFilter(
        request.GET, queryset=Complaint.objects.filter(
            active=True, reminder__lte=datetime.today()).order_by('-reminder')
    )

    paginator = Paginator(filtered_complaints.qs, 18)
    page = request.GET.get('page', 1)

    try:
        res = paginator.page(page)
    except PageNotAnInteger:
        res = paginator.page(1)
    except EmptyPage:
        res = paginator.page(paginator.num_pages)

    context = {
        "reminders_link": "active",
        'filter': filtered_complaints,
        'complaints': res
    }

    return render(request, 'admin/reminders.html', context)


@ fms_required
def fms_users(request):

    fmsUserForm = FMSUserForm(request.POST or None)

    qs = FMS.objects.filter(user__is_superuser=False).order_by(
        '-user__date_joined')

    context = {
        "fms_users_link": "active",
        'fmsUsers': qs,
        'fmsUserForm': fmsUserForm
    }

    if fmsUserForm.is_valid():
        error = fmsUserForm.save()
        if error:
            messages.error(
                request, "User already exists!")
        else:
            messages.success(
                request, "New FMS User has been registerd!")
        return redirect('admin_fms_users')

    return render(request, 'admin/fms_users.html', context)


@ fms_required
def notifications(request):

    notificationForm = NotificationForm(request.POST or None)

    qs = Notification.objects.all().order_by('-created_at')

    context = {
        "notifications_link": "active",
        'notifications': qs,

dashboard/views/Common.py
import json
from datetime import datetime

from dashboard.models import Complaint, Notification, serialize
from dashboard.views.Customers import extractComplaintObj
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import redirect


@login_required
def notif_api(request):
    if request.is_ajax():
        now = datetime.now()
        qs = Notification.objects.filter(active=True).values(
            'msg', 'created_at').order_by('-created_at')

        for q in qs:
            timediff = now - q['created_at']
            q['created_at'] = get_days(timediff.total_seconds())

        return JsonResponse({"data": list(qs)}, safe=False)
    else:
        return redirect("customer_dashboard")


@login_required
def complaint_api(request, slug):
    if request.is_ajax():
        try:
            complaint = Complaint.objects.get(complaint_id=slug)
        except:
            return JsonResponse({"status": 404}, safe=False)

        customer_info = {'name': complaint.customer.user.first_name + " " + complaint.customer.user.last_name,
                         'email': complaint.customer.user.email,
                         'contact': complaint.customer.contact}

        complaint = json.loads(serialize([complaint]))[0]
        return JsonResponse({"status": 200, "data": {**extractComplaintObj(complaint), **customer_info}}, safe=False)
    else:
        return redirect("login-redirects")


def get_days(ttime):
    day = ttime // (24 * 3600)
    ttime = ttime % (24 * 3600)
    hour = ttime // 3600
    if day:
        return ("%d days ago" % (day))
    else:
        return ("%d hrs ago" % (hour))

templates/customer/base_dashboard.html
{% extends "base_generic.html" %}
{% load static %}
{% block head %}
{% block dash_head %}{% endblock %}
{% endblock %}
{% block content %}
<div>
    <nav class="navbar navbar-light bg-white border fixed-top px-3">
        <div class="hamburger hamburger--arrowalt d-block d-lg-none mr-auto text-primary pl-0 v-center py-0 pt-1"
            type="button" onclick="toggleSidenav()">
            <span class="hamburger-box">
                <span class="hamburger-inner"></span>
            </span>
        </div>
        <a href="{% url 'customer_dashboard' %}" class="navbar-brand ml-4 pl-3 pl-lg-0 ml-lg-3 py-0">
            <img src="{% static 'images/logo.svg' %}" alt="FMS Portal IIITD" height="42px">
        </a>
        <ul class="nav ml-auto">
            <li class="nav-item dropdown v-center">
                <a class="nav-link pr-2 font-weight-light py-0" style="font-size: 1.3em" href="#" id="messageDropdown"
                    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="far fa-bell">
                        <span id="notifDot" class="d-none">&nbsp;</span>
                    </i>
                </a>
                <div class="dropdown-menu dropdown-menu-right border-0 shadow rounded-0 mt-3 customScroll"
                    class="notifDropDown" id="notificationBox" aria-labelledby="messageDropdown">
                    <a class="dropdown-item notifDropDown-item small text-center">No new notifications!</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link v-center pr-0 pr-lg-3" href="#" id="profileDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img src="https://ui-avatars.com/api/?background=47a06e&color=fff&name={{ user.first_name | lower }}+{{ user.last_name | lower }}"
                        width="30px" class="rounded-circle" alt="{{user.first_name}}">
                    <p class="mb-0 pl-2 small d-none d-lg-block pt-1">{{user.first_name}} {{user.last_name}}</p>
                </a>
                <div class="dropdown-menu dropdown-menu-right border-0 shadow rounded-0 mt-3 mr-2 mr-lg-0 small"
                    aria-labelledby="profileDropdown">
                    <a class="dropdown-item small pl-3" href="{% url 'customer_edit_profile' %}"><i
                            class="fas fa-user-edit pr-2"></i> Edit Profile</a>
                    <a class="dropdown-item small pl-3" href="{% url 'password_reset' %}"><i
                            class="fas fa-key pr-2"></i> Reset Password</a>
                    <a class="dropdown-item small pl-3" href="{% url 'logout' %}"><i
                            class="fas fa-sign-out-alt pr-2"></i> Logout</a>
                </div>
            </li>
        </ul>
    </nav>
    <div class="wrapper">
        <nav id="sidebar" class="bg-white">
            <ul class="list-unstyled" id="sidenav">
                <li class="{{ dashboard_link }} sideTab">
                    <a href="{% url 'customer_dashboard' %}"><i class="fas fa-th-large"></i>Dashboard</a>
                </li>
                <li class="{{ track_link }} sideTab">
                    <a href="{% url 'customer_track_complaint' %}"><i class="fas fa-chart-line"></i>Track
                        Complaints</a>
                </li>
            </ul>
        </nav>
        <div class="content rounded pb-4" style="background: #F2F3F7">
            {% for message in messages %}
            <div class="container-fluid p-0">
                <div class="alert {{ message.tags }} alert-dismissible mb-0" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            </div>
            {% endfor %}
            {% block page_content %} {% endblock %}
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

{% block script %}

<script type="text/javascript">
    $(".sideTab").on('click', (e) => {
        $(e.target).children().click();
    });

    $(".content").on('click', () => {
        $(".content").removeClass("show");
        $("#sidebar").removeClass("show");
        $(".hamburger").removeClass("is-active");
    });

    function toggleSidenav() {
        $(".hamburger").toggleClass("is-active");
        $(".content").toggleClass("show");
        $("#sidebar").toggleClass("show");
    }

    fetchData("{% url 'notif_api' %}", populateNotification);

    function populateNotification(notifs) {
        if (notifs.data.length != 0) {
            $("#notifDot").removeClass('d-none');
            for (var i = 0; i < notifs.data.length; i++) {
                var notifMsg = notifs.data[i].msg;
                var notifDate = notifs.data[i].created_at;
                var ele = '<div class="dropdown-item notifDropDown-item small px-3"><p class="mb-1 text-wrap">' +
                    notifMsg + '</p><p class="mb-1 text-secondary small text-right">' + notifDate + '</p></div>';
                if (i == 0) {
                    $("#notificationBox").html(ele);
                } else {
                    $("#notificationBox").append(ele);
                }
            }
        }
    }
</script>

{% block page_script %} {% endblock %}

{% endblock %}

templates/customer/dashboard.html
{% extends "customer/base_dashboard.html" %}
{% load static %}

{% load crispy_forms_tags %}

{% block page_content %}
<div class="container-fluid pt-1 pt-lg-3">
    <h2 class="text-info mb-0 font-weight-bold py-2">Register New Complaint</h2>
    <div class="row">
        <div class="col-12 col-lg-8">
            {% crispy complaintForm %}
        </div>
        <div class="col-12 col-lg-4 d-flex flex-column mt-4 mt-lg-0">
            <div class="mb-3 d-flex">
                <p class="h5 mb-0 text-info font-weight-light v-center">Complaints List</p>
                <div class="ml-auto">
                    <a href="{% url 'customer_track_complaint' %}"
                        class="btn btn-outline-success px-3 ml-1 rounded-pill btn-sm">
                        View All
                    </a>
                </div>
            </div>
            <div class="flex-grow-1 card shadow border-0">
                <div id="coreStream" class="px-3 py-3 h-100">
                    <div class="bg-info rounded p-2 font-weight-light text-white text-center h5">
                        Last Complaint
                    </div>
                    {% for complaint in complaints %}
                    {% if forloop.counter == 2%}
                    <div class="bg-info rounded p-2 font-weight-light text-white text-center h5">
                        Previous Complaints
                    </div>
                    {% endif %}
                    <div class="my-2 {% if forloop.counter == 2%}border-bottom{% endif %}">
                        <div class="card-body px-3 pb-3 pt-2">
                            <h5 class="mb-1 font-weight-bold text-truncate">#{{complaint.id}} {{complaint.location}} -
                                {{complaint.category}}
                            </h5>
                            <div class="mb-0 smaller row">
                                <div class="col">
                                    {% if complaint.active %}
                                    <span class="badge bg-success">Active</span>
                                    {% else %}
                                    <span class="badge bg-secondary">Closed</span>
                                    {% endif %}
                                </div>
                                <div class="ml-auto col-auto text-right">{{complaint.created_at}}</div>
                            </div>
                            <p class="small mb-1 mt-1">{{ complaint.desc | truncatechars:65}}</p>
                            <a href="{% url 'customer_track_complaint' %}#{{complaint.id}}"
                                class="w-100 btn btn-sm btn-outline-success">Complaint Details <i
                                    class="fas fa-arrow-right ml-1 small"></i></a>
                        </div>
                    </div>
                    {% endfor %}
                    {% if complaints %}
                    <div class="text-center small mb-1 mt-lg-2">
                        <a href="{% url 'customer_track_complaint' %}">
                            More Complaints <i class="fas fa-chevron-right ml-2 small"></i>
                        </a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block page_script %}
<script>
    var uploadField = document.getElementById("complaint_media");

    uploadField.onchange = function () {
        if (this.files[0].size > 5242880) {
            alert("File size too big! Upload file < 5Mb only.");
            this.value = "";
        };
    };
</script>
{% endblock %}

templates/customer/edit_profile.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}

<div class="bg-gradient v-center h-center px-3" style="min-height: 100vh;">
  <div class="container py-4">
    <div class="row bg-white py-5 rounded-lg shadow" style="min-height: 80vh;">

      <div class="col-12 col-lg-6 v-center h-center">
        <img src="{% static 'images/register-image.svg' %}" class="w-75" alt="Login">
      </div>

      <div class="col-12 col-lg-6 v-center h-center">
        <div style="width: 85%">
          <h2 class="text-info font-weight-bold mb-4 mb-lg-5 mt-5 mt-lg-0 text-center">Edit Profile User</h2>

          <p>To edit your email, name and password visit <a href="{{osa_main_app}}">OSA IIITD App</a>.</p>

          <form method="post" class="mb-4">
            {% csrf_token %}
            <div class="input-group mb-2 mr-sm-2 border py-2 px-3 rounded-pill input-container">
              <div class="input-group-prepend">
                <div class="input-group-text bg-transparent border-0 rounded-pill pr-0"><i
                    class="fas fa-phone text-primary" aria-hidden="true"></i></div>
              </div>
              <input type="tel" class="form-control border-0 rounded-pill bg-transparent" value="{{formData.contact}}"
                placeholder="Mobile Number" name="contact" autocapitalize="none" required="" pattern="[7-9]{1}[0-9]{9}"
                title="Phone number starting with 7-9 and remaing 9 digits between 0-9." id="id_contact">
            </div>
            <input type="submit" class="btn btn-lg btn-success rounded-pill w-100 mt-4" value="Update Profile" />
          </form>

          {% if msg.save %}
          <div class="alert alert-success small px-3 rounded-pill text-small" role="alert">
            Your profile has been updated!
          </div>
          {% endif %}

          <div class="text-center mt-4 mt-lg-5">
            <p class="text-info small font-weight-light">Looks good? Go to <a href="{% url 'customer_dashboard' %}"
                class="text-primary">Dashboard.</a></p>
          </div>

        </div>
      </div>

    </div>
  </div>
</div>
{% endblock %}